# tests/fake_cases.py


FAKE_CASES = [
    {
        "name": "Pregunta precio",
        "conversation": "",
        "last_message": "cuánto sale?",
        "current_state": "new",
        "expected_message_type": "pricing_question",
        "expected_risk_level": "low",
        "expected_next_step": "offer_demo_or_preview",
    },
    {
        "name": "Pide opt-out",
        "conversation": "",
        "last_message": "no me escribas más",
        "current_state": "new",
        "expected_message_type": "opt_out",
        "expected_risk_level": "high",
        "expected_next_step": "register_opt_out",
        "expected_do_not_do_contains": [
            "no_vender",
            "no_insistir",
            "no_volver_a_contactar",
            "registrar_opt_out",
        ],
    },
    {
        "name": "Número equivocado",
        "conversation": "",
        "last_message": "te equivocaste, este no es el local",
        "current_state": "new",
        "expected_message_type": "wrong_number",
        "expected_risk_level": "medium",
        "expected_next_step": "validate_business_number",
    },
    {
        "name": "No es dueño",
        "conversation": "",
        "last_message": "no soy el dueño, soy empleado",
        "current_state": "number_validated",
        "expected_message_type": "not_owner",
        "expected_risk_level": "medium",
        "expected_next_step": "validate_responsible_person",
    },
    {
        "name": "Pregunta quién sos",
        "conversation": "",
        "last_message": "quién sos?",
        "current_state": "new",
        "expected_message_type": "who_are_you",
        "expected_risk_level": "medium",
        "expected_next_step": "explain_montserrat",
    },
    {
        "name": "Pide demo",
        "conversation": "",
        "last_message": "pasame la demo",
        "current_state": "new",
        "expected_message_type": "demo_request",
        "expected_risk_level": "low",
        "expected_next_step": "offer_demo_or_preview",
    },
    {
        "name": "Saludo mínimo",
        "conversation": "",
        "last_message": "hola",
        "current_state": "new",
        "expected_message_type": "minimal_greeting",
        "expected_risk_level": "low",
        "expected_next_step": "explain_montserrat",
    },
    {
        "name": "Pide hablar con humano",
        "conversation": "",
        "last_message": "quiero hablar con una persona",
        "current_state": "new",
        "expected_message_type": "asks_human",
        "expected_risk_level": "medium",
        "expected_next_step": "send_to_human",
    },
{
        "name": "Pedido de soporte",
        "conversation": "",
        "last_message": "tengo un problema, no funciona",
        "current_state": "new",
        "expected_message_type": "support",
        "expected_risk_level": "high",
        "expected_next_step": "send_to_human",
        "expected_do_not_do_contains": [
            "no_vender",
            "no_seguir_automatizando",
            "derivar_a_humano",
        ],
},
    {
        "name": "Rechazo simple",
        "conversation": "",
        "last_message": "no gracias, no me interesa",
        "current_state": "new",
        "expected_message_type": "rejection",
        "expected_risk_level": "medium",
        "expected_next_step": "close_politely",
    },
    {
        "name": "Caso sensible agresivo",
        "conversation": "",
        "last_message": "esto es una estafa, los voy a denunciar",
        "current_state": "new",
        "expected_message_type": "sensitive_case",
        "expected_risk_level": "high",
        "expected_next_step": "send_to_human",
    },
    {
        "name": "Confirma que es el local",
        "conversation": "",
        "last_message": "sí, es el local",
        "current_state": "number_validation_pending",
        "expected_message_type": "confirms_business",
        "expected_risk_level": "low",
        "expected_next_step": "validate_responsible_person",
    },
    {
        "name": "Pregunta por WhatsApp",
        "conversation": "",
        "last_message": "tienen whatsapp para contacto?",
        "current_state": "new",
        "expected_message_type": "whatsapp_question",
        "expected_risk_level": "low",
        "expected_next_step": "present_short_proposal",
        "expected_extracted_data": {
            "mentioned_channels": ["whatsapp"],
        },
    },
    {
        "name": "Pregunta por menú",
        "conversation": "",
        "last_message": "tienen menú para ver?",
        "current_state": "new",
        "expected_message_type": "menu_question",
        "expected_risk_level": "low",
        "expected_next_step": "present_short_proposal",
        "expected_extracted_data": {
            "requested_features": ["menu"],
        },
    },
    {
        "name": "Pregunta por reservas",
        "conversation": "",
        "last_message": "se puede reservar?",
        "current_state": "new",
        "expected_message_type": "reservation_question",
        "expected_risk_level": "low",
        "expected_next_step": "present_short_proposal",
        "expected_extracted_data": {
            "requested_features": ["reservations"],
        },
    },
    {
        "name": "Objeción ya tiene web",
        "conversation": "",
        "last_message": "ya tenemos web, no entiendo para qué sería",
        "current_state": "new",
        "expected_message_type": "objection",
        "expected_risk_level": "medium",
        "expected_next_step": "present_short_proposal",
        "expected_objection": "already_has_website",
        "expected_extracted_data": {
            "mentioned_channels": ["web"],
        },
        "expected_do_not_do_contains": [
            "no_reemplazar_web",
            "no_descalificar_web_actual",
        ],
    },
    {
        "name": "Objeción ya está en Google Maps",
        "conversation": "",
        "last_message": "ya estamos en google maps",
        "current_state": "new",
        "expected_message_type": "objection",
        "expected_risk_level": "medium",
        "expected_next_step": "present_short_proposal",
        "expected_objection": "already_has_google_maps",
        "expected_extracted_data": {
            "mentioned_channels": ["google"],
        },
        "expected_do_not_do_contains": [
            "no_competir_con_google_maps",
            "no_descalificar_canal_actual",
        ],
    },
    {
        "name": "Mensaje confuso",
        "conversation": "",
        "last_message": "mmm no sé",
        "current_state": "new",
        "expected_message_type": "unknown",
        "expected_risk_level": "low",
        "expected_next_step": "ask_clarification",
    },
    {
        "name": "Objeción precio caro",
        "conversation": "",
        "last_message": "me parece muy caro",
        "current_state": "new",
        "expected_message_type": "objection",
        "expected_risk_level": "medium",
        "expected_next_step": "offer_demo_or_preview",
        "expected_objection": "price",
        "expected_do_not_do_contains": [
            "no_inventar_precio",
            "no_discutir",
            "no_minimizar_objecion",
            "no_dar_precio_sin_preview",
        ],
    },
    {
        "name": "Objeción falta de tiempo",
        "conversation": "",
        "last_message": "ahora no puedo, no tengo tiempo",
        "current_state": "new",
        "expected_message_type": "objection",
        "expected_risk_level": "medium",
        "expected_next_step": "schedule_followup",
        "expected_objection": "no_time",
        "expected_do_not_do_contains": [
            "no_mandar_mensaje_largo",
            "no_pedir_reunion_ahora",
        ],
    },
]
